### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by QGB** [Depau/wi-se-sw#1]
```
docker run -it -v /root:/root -v /home:/home -v/mnt:/mnt -w $PWD  petewall/platformio  login
docker ps
docker exec ID bash

cd /mnt/test/github/wi-se-sw/
/mnt/test/github/wi-se-sw/builder.py prepare --example  #generate follow dir
cd /mnt/test/github/wi-se-sw/.builder/config.yml

### modify C:\test\github\wi-se-sw\configs\config.yml.example

/mnt/test/github/wi-se-sw/builder.py prepare --example;pio run

DOWNLOAD TOOL v3.6.4
C:\test\github\wi-se-sw\.builder\config.yml\.pio\build\wi_se\firmware.bin                0x0
===
```
Building in release mode
Compiling .pio/build/wi_se/src/ExtendedSerial.cpp.o
Compiling .pio/build/wi_se/src/main.cpp.osrc/ExtendedSerial.cpp:49: warning: ignoring '#pragma clang diagnostic' [-Wunknown-pragmas]
   49 | #pragma clang diagnostic push
      | 
src/ExtendedSerial.cpp:50: warning: ignoring '#pragma clang diagnostic' [-Wunknown-pragmas]
   50 | #pragma clang diagnostic ignored "-Wint-to-pointer-cast"
      | 
src/ExtendedSerial.cpp:58: warning: ignoring '#pragma clang diagnostic' [-Wunknown-pragmas]
   58 | #pragma clang diagnostic pop      | 
In file included from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h:40,
                 from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ArduinoOTA/ArduinoOTA.h:4,
                 from src/main.cpp:2:
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h:68:34: error: expected class-name before '{' token
   68 | class WiFiServer : public Server {
      |                                  ^
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h:97:16: error: type 'Print' is not a base type for type 'WiFiServer'
   97 |   using Print::write;
      |                ^~~~~
src/main.cpp: In function 'void setup()':
src/main.cpp:103:58: warning: null argument where non-null required (argument 2) [-Wnonnull]
  103 |             strncpy(wifiSsid, WIFI_SSID, sizeof(wifiSsid));
      |                                                          ^
Compiling .pio/build/wi_se/src/server.cpp.o
Compiling .pio/build/wi_se/src/ttyd.cpp.o
*** [.pio/build/wi_se/src/main.cpp.o] Error 1
In file included from include/ttyd.h:8,
                 from include/Server.h:8,
                 from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h:31,
                 from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h:40,
                 from .pio/libdeps/wi_se/ESP Async WebServer/src/ESPAsyncWebServer.h:35,
                 from src/server.cpp:6:

....

      |     ^~~~~~~~~~~~~~                                                                                                                                                        [0/1464]
      |     AsyncServer
include/Server.h:45:29: error: 'AsyncWebServer' has not been declared
   45 |     WiSeServer(char *token, AsyncWebServer *httpd, AsyncWebSocket *websocket, TTY *ttyd) :
      |                             ^~~~~~~~~~~~~~
include/Server.h:58:36: error: 'AsyncWebServerRequest' has not been declared
   58 |     static bool checkHttpBasicAuth(AsyncWebServerRequest *request);
      |                                    ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:60:29: error: 'AsyncWebServerRequest' has not been declared
   60 |     static void handleIndex(AsyncWebServerRequest *request);
      |                             ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:62:29: error: 'AsyncWebServerRequest' has not been declared
   62 |     void handleStatsRequest(AsyncWebServerRequest *request) const;
      |                             ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:64:28: error: 'AsyncWebServerRequest' has not been declared
   64 |     void handleSttyRequest(AsyncWebServerRequest *request) const;
      |                            ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:66:25: error: 'AsyncWebServerRequest' has not been declared
   66 |     void handleSttyBody(AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) const;
      |                         ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:68:27: error: 'AsyncWebServerRequest' has not been declared
   68 |     void sttySendResponse(AsyncWebServerRequest *request) const;
      |                           ^~~~~~~~~~~~~~~~~~~~~
include/Server.h:70:22: error: 'AsyncWebServerRequest' has not been declared
   70 |     void handleToken(AsyncWebServerRequest *request) const;
      |                      ^~~~~~~~~~~~~~~~~~~~~
include/Server.h: In constructor 'WiSeServer::WiSeServer(char*, int*, AsyncWebSocket*, TTY*)':
include/Server.h:47:13: error: class 'WiSeServer' does not have any field named 'httpd'
   47 |             httpd{httpd},
      |             ^~~~~
In file included from /root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h:40,
                 from .pio/libdeps/wi_se/ESP Async WebServer/src/ESPAsyncWebServer.h:35,
                 from src/server.cpp:6:
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h: At global scope:
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h:68:34: error: expected class-name before '{' token
   68 | class WiFiServer : public Server {
      |                                  ^
/root/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src/WiFiServer.h:97:16: error: type 'Print' is not a base type for type 'WiFiServer'
   97 |   using Print::write;
      |                ^~~~~
^C*** [.pio/build/wi_se/src/ttyd.cpp.o] Build interrupted.
*** [.pio/build/wi_se/src/server.cpp.o] Build interrupted.
Error: Aborted by user
```

**Comment by depau** [comment]
That's not how it's supposed to be built: https://github.com/Depau/wi-se-sw#building-and-flashing

**Comment by QGB** [comment]
@Depau 
rename 'server.h' fix the problem

https://esp8266.ru/forum/threads/platformio-kak-razbit-kod-na-fajly.5392/

**Comment by QGB** [comment]
@Depau Do you have any plans to port this code to support ESP32 or ESP32C3?

**Comment by QGB** [comment]
```
root@1a26bc21587d:/home/qgb/github/ttyd/html# yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error jest-worker@29.1.2: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "16.3.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by QGB** [comment]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/qgb/github/ttyd/html/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 4.15.0-193-generic
gyp ERR! command "/usr/local/bin/node" "/home/qgb/github/ttyd/html/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/qgb/github/ttyd/html/node_modules/node-sass
gyp ERR! node -v v18.10.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by QGB** [comment]
"^7.0.2", 有 linux-x64-93_binding.node
```
verbose 1723.550785013 Removing extraneous file "/home/qgb/github/ttyd/html/node_modules/node-gyp/gyp/pylib/gyp/__pycache__/simple_copy.cpython-39.pyc".
verbose 1723.551718955 Removing extraneous file "/home/qgb/github/ttyd/html/node_modules/node-gyp/gyp/pylib/gyp/__pycache__/xcode_emulation.cpython-39.pyc".
verbose 1723.552592507 Removing extraneous file "/home/qgb/github/ttyd/html/node_modules/node-gyp/gyp/pylib/gyp/generator/__pycache__".
verbose 1723.555070566 Removing extraneous file "/home/qgb/github/ttyd/html/node_modules/node-gyp/gyp/pylib/gyp/generator/__pycache__/__init__.cpython-39.pyc".
verbose 1723.556137761 Removing extraneous file "/home/qgb/github/ttyd/html/node_modules/node-gyp/gyp/pylib/gyp/generator/__pycache__/make.cpython-39.pyc".
[4/4] Building fresh packages...
[1/2] _ es5-ext
[-/2] _ waiting...
verbose 1787.317272701 Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-93_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-93_binding.node": 

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

[-/2] _ waiting...
[2/2] _ node-sass
```
